using System;
using System.ComponentModel.DataAnnotations;

namespace BlockchainPatientData.Models
{
    /// <summary>
    /// Patient Model with NFT-based Health ID
    /// Each patient gets a unique NFT token for blockchain identity
    /// </summary>
    public class Patient
    {
        [Key]
        public int PatientID { get; set; }

        [Required(ErrorMessage = "Patient name is required")]
        [StringLength(100)]
        public string Name { get; set; } = string.Empty;

        [Required]
        [Range(1, 150, ErrorMessage = "Age must be between 1 and 150")]
        public int Age { get; set; }

        [Required]
        public string Gender { get; set; } = string.Empty;

        // NFT_ID is generated by server, not required from form
        [StringLength(50)]
        public string NFT_ID { get; set; } = string.Empty;

        [StringLength(200)]
        public string? Address { get; set; }

        [Phone]
        [StringLength(15)]
        public string? PhoneNumber { get; set; }

        [EmailAddress]
        [StringLength(100)]
        public string? Email { get; set; }

        [StringLength(5)]
        public string? BloodGroup { get; set; }

        public DateTime CreatedAt { get; set; } = DateTime.Now;

        /// <summary>
        /// Generates a unique NFT-based Health ID for the patient
        /// </summary>
        public static string GenerateNFT_ID()
        {
            return "NFT-" + Guid.NewGuid().ToString("N").Substring(0, 8).ToUpper();
        }
    }
}
